<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Login with Password</name>
   <tag></tag>
   <elementGuidId>3ec85b63-1655-4abf-a6a6-49f50a1a7270</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-primary.btn-block.mb-2.ng-tns-c197-2.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9670faca-3449-4099-bde2-b300757e753c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>043a174f-3381-4dcb-9bde-2ad764f97243</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-block mb-2 ng-tns-c197-2 ng-star-inserted</value>
      <webElementGuid>3bd313e4-f048-4e23-a51d-c8cfa58da6cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Login with Password </value>
      <webElementGuid>116edae1-1a56-408f-b949-5103f88211a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;layoutAuthentication_content&quot;)/main[1]/div[@class=&quot;container&quot;]/div[@class=&quot;row justify-content-center ng-tns-c197-2&quot;]/div[@class=&quot;col-xl-6 col-lg-10 col-sm-12 ng-tns-c197-2&quot;]/div[@class=&quot;card shadow-lg border-0 rounded-lg mt-5 ml-auto mr-auto ng-tns-c197-2&quot;]/div[@class=&quot;card-body ng-tns-c197-2 block-ui__element ng-star-inserted&quot;]/form[@class=&quot;ng-tns-c197-2 ng-star-inserted ng-dirty ng-touched ng-valid&quot;]/button[@class=&quot;btn btn-primary btn-block mb-2 ng-tns-c197-2 ng-star-inserted&quot;]</value>
      <webElementGuid>2afbdf72-33bb-4db2-8a16-d6578f0a987d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>58d8ca5a-1201-4cae-bdc1-5ee6870df92a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layoutAuthentication_content']/main/div/div/div/div[2]/div[2]/form/button</value>
      <webElementGuid>4f2455df-83bd-44e0-8257-1073d8abaa45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/following::button[1]</value>
      <webElementGuid>a0630262-bc37-430d-bee1-fe5a75719107</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/following::button[1]</value>
      <webElementGuid>6d21a7b8-851b-4e58-ab33-89787f0f2997</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot Password?'])[1]/preceding::button[1]</value>
      <webElementGuid>931629d7-7567-4456-ba5a-bfdf7b29e3e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copyright © 2023 Hallmark Health Care Solutions Inc.'])[1]/preceding::button[1]</value>
      <webElementGuid>c0014a4a-3c46-403e-91ac-95eaa2eb16b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Login with Password']/parent::*</value>
      <webElementGuid>5d5b635c-ab88-4dd4-9d82-b09a10329835</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>c8a14248-1560-47d2-a4db-3ace3fe8cdf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = ' Login with Password ' or . = ' Login with Password ')]</value>
      <webElementGuid>a1886aa3-16b6-43f2-9cee-e04f1c5ffa55</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
