<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Automation</name>
   <tag></tag>
   <elementGuidId>d2de10ea-bc8f-4258-ab2a-3b7360835992</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#a58ec4b18a4c-5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='a58ec4b18a4c-5']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>48a72007-6a1f-4035-bcdd-365719c9be9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-option ng-star-inserted ng-option-marked</value>
      <webElementGuid>7838b12b-ceb3-4d5a-a53e-d621d4bf8ba6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>684a4f89-d2c0-4326-89ee-08985f10539f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>a58ec4b18a4c-5</value>
      <webElementGuid>540dc357-64c1-425f-a3f4-3df6faaa3b9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Automation </value>
      <webElementGuid>f8644848-25ae-4a6e-81fd-ff779c311563</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a58ec4b18a4c-5&quot;)</value>
      <webElementGuid>759f9791-22b4-491a-9c7d-5538cc99b0a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='a58ec4b18a4c-5']</value>
      <webElementGuid>25c4793f-a1d4-44f3-b9fc-32a7d4a01de6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-dropdown-panel[@id='a58ec4b18a4c']/div/div[2]/div[6]</value>
      <webElementGuid>e20de91e-8597-4e50-a65f-6a3be4d76fbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BH'])[1]/following::div[1]</value>
      <webElementGuid>c358df00-eabc-4da2-bd74-1a5434e4d05c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Demo'])[1]/following::div[2]</value>
      <webElementGuid>d5fe2149-2637-4b68-a506-578ed77bda5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Role'])[1]/preceding::div[1]</value>
      <webElementGuid>8b2143a1-4584-4087-bab6-462c338a6bd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]</value>
      <webElementGuid>91ed8a7f-c815-4d8f-a66c-209f4819a163</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'a58ec4b18a4c-5' and (text() = 'Automation ' or . = 'Automation ')]</value>
      <webElementGuid>948c6ba8-c1d4-4cdc-bac5-52f603ea0615</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
