<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div</name>
   <tag></tag>
   <elementGuidId>985cb3bd-f57a-4b0a-bf33-a99bd5e8b9d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menu-dropdown > div</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[5]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1c0116d6-57ad-4907-be2e-6157118b31a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>fa73e2fe-452d-4f66-a6bd-749a6965217b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-dropdown&quot;)/div[1]</value>
      <webElementGuid>911efdfd-a996-4ee1-8c39-cf6856ac386a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu-dropdown']/div</value>
      <webElementGuid>db605c22-e014-477d-993f-c359227fef21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div</value>
      <webElementGuid>4f003bfb-1a8b-4eec-aeab-b8b8a9d7b8a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
