<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Starting a New Form_submission-search</name>
   <tag></tag>
   <elementGuidId>d253485d-4ee0-4c51-8b4e-496149d74f08</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='submission-search']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;submission-search&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b5169532-8fe7-4cad-8613-216bfe8d05d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>submission-search</value>
      <webElementGuid>0308ad8b-c236-4446-8aff-54d0ec918522</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>new-submission-search</value>
      <webElementGuid>380f84ee-e3af-4cf5-9129-25432f627eec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search by form name</value>
      <webElementGuid>ef39056f-ac24-4f6b-a523-2619b9290de1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;hydrated&quot;]/body[1]/div[4]/div[@class=&quot;renderer-MuiDialogContent-root mirata-modal-card&quot;]/div[@class=&quot;new-submission-layout&quot;]/div[@class=&quot;new-submission-header&quot;]/div[@class=&quot;new-submission-search-bar&quot;]/input[@class=&quot;new-submission-search&quot;]</value>
      <webElementGuid>21e9004a-3e1b-4d47-ae2b-da0d6212ebe7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='submission-search']</value>
      <webElementGuid>f9930c51-268e-4d29-88f6-6d72aff05a72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>e7fa38a8-7557-4c0e-b889-5b809de80c08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'submission-search' and @placeholder = 'Search by form name']</value>
      <webElementGuid>7b6baf9b-2428-4621-94f0-e308d07dcc65</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
