<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ul_Copy of aTL_construction water leak repo_8e1206</name>
   <tag></tag>
   <elementGuidId>9a6af037-f34b-4e58-9abb-12682c49093e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='inbox-list-item-holder']/ul</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ul.renderer-MuiList-root.inbox-main-list.renderer-MuiList-padding</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ul</value>
      <webElementGuid>f9b26d9d-b3c7-46db-8bf1-cf62942caee7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>renderer-MuiList-root inbox-main-list renderer-MuiList-padding</value>
      <webElementGuid>1084e1ac-b17e-4833-8168-52768eca1ce1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Copy of aTL_construction water leak reportAssigned06/15A_List_Sigcreated06/15</value>
      <webElementGuid>6c608db4-6c59-4e71-808c-324bcfd770f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inbox-list-item-holder&quot;)/ul[@class=&quot;renderer-MuiList-root inbox-main-list renderer-MuiList-padding&quot;]</value>
      <webElementGuid>2967ce24-88bf-495d-af3c-aee8c2fdf033</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='inbox-list-item-holder']/ul</value>
      <webElementGuid>e96a31ad-856e-4235-a0b7-ba31106fa4b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Form Lists'])[1]/following::ul[1]</value>
      <webElementGuid>a783c58f-d4cb-4481-95f0-32344687def1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kavita Bhatt'])[4]/following::ul[1]</value>
      <webElementGuid>631dbf10-c099-4c17-888a-93910ffcdf17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[2]/ul</value>
      <webElementGuid>b42ff8b6-8d4c-4e18-a522-dd0bb6ce2abd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ul[(text() = 'Copy of aTL_construction water leak reportAssigned06/15A_List_Sigcreated06/15' or . = 'Copy of aTL_construction water leak reportAssigned06/15A_List_Sigcreated06/15')]</value>
      <webElementGuid>19534dff-180b-408a-84e5-aa561b1c3342</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
