<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_RID_12345_grid_474636511_0Delete_0_g_94d48b</name>
   <tag></tag>
   <elementGuidId>0f7a1d2c-a484-462a-afbb-6c07d72ff26e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#grid_474636511_0Delete_0_gridcommand6</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='grid_474636511_0Delete_0_gridcommand6']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>50ac53b9-3da9-416d-a297-09f02fdc59a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>grid_474636511_0Delete_0_gridcommand6</value>
      <webElementGuid>c9f699e1-5c53-48df-bac3-a63eb2ffc6b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b937fe19-3a95-48aa-a0db-f069a4cab98d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Delete</value>
      <webElementGuid>768d4f8c-58e6-4f7e-9d74-c05f9bb0338e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-uid</name>
      <type>Main</type>
      <value>gridcommand6</value>
      <webElementGuid>5e764e72-5a90-4cc4-96e0-060edb208b7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>e-lib e-btn e-control btn btn-outline-danger border-0 btn-icon rounded e-icon-btn e-edit-delete e-deletebutton</value>
      <webElementGuid>8bd32369-ca53-42ba-9b3d-22d9d01c8965</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;grid_474636511_0Delete_0_gridcommand6&quot;)</value>
      <webElementGuid>a051e9a0-a03c-468a-a1bf-1ba149612566</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='grid_474636511_0Delete_0_gridcommand6']</value>
      <webElementGuid>3834bca2-1fb4-49b9-825e-ad07eb2723d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='grid_474636511_0_content_table']/tbody/tr/td[5]/div/button[2]</value>
      <webElementGuid>63880681-0f31-4857-8a2b-e2df329c3399</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RID_12345'])[1]/following::button[2]</value>
      <webElementGuid>276a970b-b3a7-47db-88bd-00f2e977197a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reg_12345'])[1]/following::button[2]</value>
      <webElementGuid>0eec8ddc-ef0b-4478-970c-bb69f39dc8f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='...'])[1]/preceding::button[3]</value>
      <webElementGuid>12c0b8d5-6231-4da1-9339-cf8a8ff17a3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='...'])[2]/preceding::button[3]</value>
      <webElementGuid>517604b5-46db-4932-8884-cc61a0c3eaf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/div/button[2]</value>
      <webElementGuid>50e2ed1e-9a31-417a-8dc0-7e15de80912d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'grid_474636511_0Delete_0_gridcommand6' and @type = 'button' and @title = 'Delete']</value>
      <webElementGuid>f4b51c43-71a4-4a07-835d-ad1bf8372a04</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
