<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_DeletedRegion deleted</name>
   <tag></tag>
   <elementGuidId>6400bc2d-2a5b-4832-9033-cd34a787e5dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.p-toast-message-content.ng-tns-c141-7</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='layoutSidenav_content']/main/app-region/p-toast/div/p-toastitem/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a4704501-026e-4f9a-975e-7a2449942882</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>alert</value>
      <webElementGuid>18c79a4f-4168-40b8-ab05-53e90f0ac9bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>assertive</value>
      <webElementGuid>a98b0368-933c-4408-906e-ececc0dd44b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-atomic</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8c54f445-57da-4b91-97fe-0251a2532f81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-toast-message-content ng-tns-c141-7</value>
      <webElementGuid>823ed12e-9a72-4dc5-981b-74819b7de1c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DeletedRegion deleted</value>
      <webElementGuid>24c8bbe8-ccd4-44fa-8e21-2e85fcb15671</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;layoutSidenav_content&quot;)/main[@class=&quot;h-100&quot;]/app-region[@class=&quot;ng-star-inserted&quot;]/p-toast[@class=&quot;p-element ng-tns-c142-5 ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c142-5 p-toast p-component p-toast-bottom-right&quot;]/p-toastitem[@class=&quot;p-element ng-tns-c141-7 ng-trigger ng-trigger-toastAnimation ng-tns-c142-5 ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c141-7 ng-trigger ng-trigger-messageState p-toast-message-success p-toast-message&quot;]/div[@class=&quot;p-toast-message-content ng-tns-c141-7&quot;]</value>
      <webElementGuid>21407f80-2edb-47dd-8c61-00a745fc4d4c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layoutSidenav_content']/main/app-region/p-toast/div/p-toastitem/div/div</value>
      <webElementGuid>8f9b1e75-17e5-4a3d-a2d1-fcb92fd95d69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Items per page'])[1]/following::div[3]</value>
      <webElementGuid>6c31ce58-36f4-4b0f-8660-e678a3a4ec6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(0 item)'])[1]/following::div[8]</value>
      <webElementGuid>b74db4f9-3969-4a40-bd7c-aed5a5061e88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p-toastitem/div/div</value>
      <webElementGuid>d6f16812-dcba-4aa9-b379-3314ea133eec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'DeletedRegion deleted' or . = 'DeletedRegion deleted')]</value>
      <webElementGuid>a63329c2-95fb-4461-87b9-b1e8d6c43852</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
