<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_grid_474636511_0_header_table_Name</name>
   <tag></tag>
   <elementGuidId>9b34e8bf-112d-42de-8f48-c559bc9554e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#grid_474636511_0Name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='grid_474636511_0Name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f3b95c56-4c0a-478d-937d-d377b0a5c71e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>e-field e-input e-defaultcell e-control e-textbox e-lib e-error</value>
      <webElementGuid>29a52ba6-8087-4a53-baac-c640b5a8211b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0df1dff8-edb8-40c0-81c5-a4e1bf92b3a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>grid_474636511_0Name</value>
      <webElementGuid>4e4bb3a6-4c4f-415b-8b51-c4690d59fa2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Name</value>
      <webElementGuid>774009b1-d0c5-408d-a5ff-4899f4504b66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>e-mappinguid</name>
      <type>Main</type>
      <value>grid-column1</value>
      <webElementGuid>ebd2f0ad-bf6f-411d-b820-f5122ff577a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>5ec862e6-66d7-4f2c-acf1-1699f00e44ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>01826ae0-6b0a-4dc5-ac3b-d55d3f537be7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>grid_474636511_0Name-info</value>
      <webElementGuid>828f51aa-d34c-49b3-8232-84d2657030b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8c6bf896-8011-48dc-98b7-fc0e08455556</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;grid_474636511_0Name&quot;)</value>
      <webElementGuid>ecab83e2-4e82-4961-b79b-275e862c1972</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='grid_474636511_0Name']</value>
      <webElementGuid>fcd5fce1-af34-41c8-a542-2e5c095a4de5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='grid_474636511_0EditForm']/table/tbody/tr/td[2]/span/input</value>
      <webElementGuid>e43bbb91-d817-40ec-9837-481ee0f77262</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/span/input</value>
      <webElementGuid>5a86eaa2-fce8-4564-80e3-27c879699110</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'grid_474636511_0Name' and @name = 'Name']</value>
      <webElementGuid>985e6f67-b0ae-46a5-807d-bb35f810343e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
