<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_grid_474636511_0_header_table_RegionId</name>
   <tag></tag>
   <elementGuidId>c2e18545-bc9d-4105-b4e7-7491465afd71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#grid_474636511_0RegionId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='grid_474636511_0RegionId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f835d207-0e7f-4105-b8b8-6c4f5b0c7629</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>e-field e-input e-defaultcell e-control e-textbox e-lib e-error</value>
      <webElementGuid>0fc4a1e7-9aef-4ef9-a000-17bd36b9e738</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>18d7af5e-2b48-479b-83a7-a1d3ff21469a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>grid_474636511_0RegionId</value>
      <webElementGuid>a7920484-eb18-414e-a986-cb9e1df93e53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>RegionId</value>
      <webElementGuid>ea55dac2-c132-4a80-9e81-56e4e8e27380</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>e-mappinguid</name>
      <type>Main</type>
      <value>grid-column2</value>
      <webElementGuid>d6a2f527-ba85-44d0-ad00-4abffa6e1a37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>594c4970-d22e-4e1d-a18f-2e9404254535</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>522b9593-8c16-49a3-a18c-987b4411eb83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>grid_474636511_0RegionId-info</value>
      <webElementGuid>46048960-8fd1-4638-927d-5dadc288e918</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d373be5f-187e-4b7a-80f2-7e1fc28a5698</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;grid_474636511_0RegionId&quot;)</value>
      <webElementGuid>dcd4027f-5ba6-4507-ae6f-aaa5fbb1bafb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='grid_474636511_0RegionId']</value>
      <webElementGuid>c2f85d1d-9dc9-4d72-b9cd-ccf440b3af48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='grid_474636511_0EditForm']/table/tbody/tr/td[3]/span/input</value>
      <webElementGuid>14678b7c-047b-4b8b-8dbc-9de05002858d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/span/input</value>
      <webElementGuid>9d90b532-5836-4105-a982-8d575505eafd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'grid_474636511_0RegionId' and @name = 'RegionId']</value>
      <webElementGuid>69338a5c-794d-4611-b463-8340b19f5f20</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
