<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_grid_474636511_0_header_table_e-btn-ic_ff60e2</name>
   <tag></tag>
   <elementGuidId>af58d38e-d3bb-44cd-809a-2cf494720e50</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.e-btn-icon.fas.fa-save</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='grid_474636511_0Save_0_gridcommand7']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>39f753b4-95ed-488b-ab40-19692217a4e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>e-btn-icon fas fa-save</value>
      <webElementGuid>206ef0fe-2e44-46c7-8973-9bac86e44ec0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;grid_474636511_0EditForm&quot;)/table[@class=&quot;e-table e-inline-edit&quot;]/tbody[1]/tr[1]/td[@class=&quot;e-rowcell e-unboundcell&quot;]/div[@class=&quot;e-unboundcelldiv&quot;]/button[@id=&quot;grid_474636511_0Save_0_gridcommand7&quot;]/span[@class=&quot;e-btn-icon fas fa-save&quot;]</value>
      <webElementGuid>aa59209b-5ce2-485b-b6d3-88aaaa06fd43</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='grid_474636511_0Save_0_gridcommand7']/span</value>
      <webElementGuid>22d0cff4-1f8e-4ffc-87d6-e50cbddc04e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[3]/span</value>
      <webElementGuid>4d30db6c-54ed-45aa-a543-184e8e261079</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
