<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Login</name>
   <tag></tag>
   <elementGuidId>11079f9f-6143-4db1-a11c-84f99ec2bf2e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-primary.btn-block.ng-tns-c197-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6ea4d802-737f-4f76-a0e5-0143df960220</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cy</name>
      <type>Main</type>
      <value>loginButton</value>
      <webElementGuid>d8e03a9b-6094-4003-881d-293d7691dbf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>1a9ce6fd-5d32-47b5-ab2a-65119617d494</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-block ng-tns-c197-2</value>
      <webElementGuid>55be2b76-3604-4599-ad66-66267953ed36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Login </value>
      <webElementGuid>c32ca60b-bb4c-435f-8b63-d65cd02328c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;layoutAuthentication_content&quot;)/main[1]/div[@class=&quot;container&quot;]/div[@class=&quot;row justify-content-center ng-tns-c197-2&quot;]/div[@class=&quot;col-xl-6 col-lg-10 col-sm-12 ng-tns-c197-2&quot;]/div[@class=&quot;card shadow-lg border-0 rounded-lg mt-5 ml-auto mr-auto ng-tns-c197-2&quot;]/div[@class=&quot;card-body ng-tns-c197-2 block-ui__element ng-star-inserted&quot;]/form[@class=&quot;ng-tns-c197-2 ng-star-inserted ng-dirty ng-touched ng-valid ng-submitted&quot;]/div[@class=&quot;form-group d-flex align-items-center justify-content-between mt-4 mb-0 ng-tns-c197-2 ng-star-inserted&quot;]/button[@class=&quot;btn btn-primary btn-block ng-tns-c197-2&quot;]</value>
      <webElementGuid>63c496dc-1d22-49f8-bb2c-dd22b9416b2c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>e8cad14d-cbbd-4805-afa8-b1af4bc3a172</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layoutAuthentication_content']/main/div/div/div/div[2]/div[2]/form/div[2]/button</value>
      <webElementGuid>5d73adac-2b82-4a51-89fd-a5cb20620cb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='System Administrator1'])[1]/following::button[1]</value>
      <webElementGuid>e225e245-4176-422c-bb53-25312adc6152</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Role'])[1]/following::button[1]</value>
      <webElementGuid>3cbd04b3-5ff5-4919-85c0-6a0e405cc268</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot Password?'])[1]/preceding::button[1]</value>
      <webElementGuid>9ea1b088-fc15-4496-a54b-534ecb6c8294</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copyright © 2023 Hallmark Health Care Solutions Inc.'])[1]/preceding::button[1]</value>
      <webElementGuid>6f6f29c5-2d35-420c-a50c-1262dc94db97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Login']/parent::*</value>
      <webElementGuid>1b817d6e-8f20-47d3-9114-e752bd4cff6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>2f229276-54a9-4592-8188-b3203fa88fdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = ' Login ' or . = ' Login ')]</value>
      <webElementGuid>6f9e6fee-c998-4a48-bdce-4b40d50754e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
