<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Automation_1</name>
   <tag></tag>
   <elementGuidId>02caa160-0b03-4b60-916e-348f87ab667a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#af4f83acdeea-5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='af4f83acdeea-5']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>269173a9-0410-4920-b01b-6362838c9f5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-option ng-star-inserted ng-option-marked</value>
      <webElementGuid>db26e6f3-4489-4444-acc3-24493ac8448d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>6e007710-542d-4686-8991-142e3fa5fc04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>af4f83acdeea-5</value>
      <webElementGuid>a6bcd681-beb9-4fa4-aae7-0ba4d495709a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Automation </value>
      <webElementGuid>c58c292e-0fbb-4c17-aef3-9e2bafdf8a98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;af4f83acdeea-5&quot;)</value>
      <webElementGuid>37b4e9cb-c673-462a-ab4c-66b4e81aea62</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='af4f83acdeea-5']</value>
      <webElementGuid>68b745c2-c1b8-4723-b9c2-b3b6c67ae30f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-dropdown-panel[@id='af4f83acdeea']/div/div[2]/div[6]</value>
      <webElementGuid>883ed7ae-158a-47e5-8b47-f7f04c8ef1a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BH'])[1]/following::div[1]</value>
      <webElementGuid>f82c2550-e891-4407-9bff-565fa1170a9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Demo'])[1]/following::div[2]</value>
      <webElementGuid>9cfbf154-c61f-4d65-83db-b405e726229d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Role'])[1]/preceding::div[1]</value>
      <webElementGuid>1f38c221-84b2-4571-96d2-f495bb6ff13b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]</value>
      <webElementGuid>2e845a86-57dd-46e3-85eb-1502d1d8da53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'af4f83acdeea-5' and (text() = 'Automation ' or . = 'Automation ')]</value>
      <webElementGuid>6a1770b0-3603-4900-bd60-93aeab3dcdfe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
