<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Contract Management Please select an Or_fa4c31</name>
   <tag></tag>
   <elementGuidId>812396f3-9d22-4f6a-94f0-53dadcadb912</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.row.justify-content-center.ng-tns-c197-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='layoutAuthentication_content']/main/div/div/div/div[2]/div[2]/form/div/div[3]/ng-select/div/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8d4d052a-f1e2-4bb3-bb4c-0cdc53d495cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row justify-content-center ng-tns-c197-2</value>
      <webElementGuid>da8aac36-6f13-43ab-9068-8b8929b5812d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Contract Management Please select an Organization and Role below. Organization×Automation ×Role×System Administrator1 × Login Forgot Password?</value>
      <webElementGuid>d3db6588-5d50-4636-8466-a419bc7f47a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;layoutAuthentication_content&quot;)/main[1]/div[@class=&quot;container&quot;]/div[@class=&quot;row justify-content-center ng-tns-c197-2&quot;]</value>
      <webElementGuid>bb418183-9209-4644-896b-01de94af7729</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layoutAuthentication_content']/main/div/div</value>
      <webElementGuid>d9a5bbc4-7e93-4dfb-ae3e-05067cc4a5a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div/div</value>
      <webElementGuid>ca170539-d8a3-48c9-8d36-5e581ebb4d53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Contract Management Please select an Organization and Role below. Organization×Automation ×Role×System Administrator1 × Login Forgot Password?' or . = 'Contract Management Please select an Organization and Role below. Organization×Automation ×Role×System Administrator1 × Login Forgot Password?')]</value>
      <webElementGuid>8874d01b-2109-42a6-80be-28c278eafb5a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
