<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_inputPassword</name>
   <tag></tag>
   <elementGuidId>20bfa0f4-b5e4-4312-9a07-7642b9405de5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputPassword</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputPassword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d82779ad-f58d-48ee-840e-b18c88d64601</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputPassword</value>
      <webElementGuid>7096a241-f31f-44b0-a2b1-0686235b7f30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cy</name>
      <type>Main</type>
      <value>passwordInput</value>
      <webElementGuid>c13b13c9-059f-4d93-b292-f84692909866</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>75df4607-3972-4a70-a480-0863779cf15f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>30ae1ecd-6ac4-4a57-b307-4eac9870ff82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>fd3b056e-596d-4121-b631-4539b3825ec4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control py-4 ng-tns-c197-2 ng-untouched ng-dirty ng-valid</value>
      <webElementGuid>34345bb4-6921-4f5a-a89b-7ebb87ce2bb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputPassword&quot;)</value>
      <webElementGuid>e7751e7d-7868-4087-9e1e-644ddfbf5191</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputPassword']</value>
      <webElementGuid>d4e699ed-aa2c-496d-9980-e4c348e874cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layoutAuthentication_content']/main/div/div/div/div[2]/div[2]/form/div/div[2]/input</value>
      <webElementGuid>bdfe857c-8d13-47a5-b5bf-c7f1f503ecde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>e4e42e7d-498f-4f77-abb8-be1ecc2ddd16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'inputPassword' and @type = 'password' and @placeholder = 'Password']</value>
      <webElementGuid>774a959f-ed1a-49ce-987f-c2755ace623d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
