<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Site Types</name>
   <tag></tag>
   <elementGuidId>f8907213-1cf1-4089-94bb-994021a75c25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='nav-dropdown-right']/li[9]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0c63eac7-e987-4476-b69e-0dc4f1974589</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/hauler/site-types</value>
      <webElementGuid>13da6a53-bc17-43e4-967c-a9fcb32b6e9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Site Types</value>
      <webElementGuid>e5be0ee8-79f3-4388-a49f-df505f8d17fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-dropdown-right&quot;)/li[9]/a[1]</value>
      <webElementGuid>ea391beb-0b9b-4229-ac74-61facaabfcfb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='nav-dropdown-right']/li[9]/a</value>
      <webElementGuid>2176acbd-c826-4353-b562-444c45d2a021</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Site Types')]</value>
      <webElementGuid>eadd8214-2a28-4fa3-89a3-97b012b8059f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asset Types'])[1]/following::a[1]</value>
      <webElementGuid>e2a9152b-b68f-43c4-a880-986ff90c6bb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ticket Types'])[1]/following::a[2]</value>
      <webElementGuid>3e3e46f0-baba-42ae-aa43-82c6a1d3fcf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sites'])[1]/preceding::a[1]</value>
      <webElementGuid>3673cf24-a5c7-4596-9733-625dceb5c9a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fee Types'])[1]/preceding::a[2]</value>
      <webElementGuid>49d72103-760f-4394-b884-8fe348a5a220</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Site Types']/parent::*</value>
      <webElementGuid>fbcbaca1-208f-4b4f-97c4-2f97fdada666</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/hauler/site-types')]</value>
      <webElementGuid>257555b9-58e8-42b6-b7ac-55b4f54082a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[11]/ul/li[9]/a</value>
      <webElementGuid>f6e91366-34c4-4360-a8a2-fd24aa692bf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/hauler/site-types' and (text() = 'Site Types' or . = 'Site Types')]</value>
      <webElementGuid>4f414dcb-f388-46e5-8bde-a12d81f719e3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
