<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_mode_edit</name>
   <tag></tag>
   <elementGuidId>65f9e587-9cf3-42fe-ab3e-2a88903e680a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/div[2]/div[2]/div/div[2]/div/div[2]/h4/button/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>46d0f133-16c5-4295-986f-b1d5f1c085fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>material-icons pull-right thumbster-button-icon</value>
      <webElementGuid>1ccc3b61-48bc-4784-b6ce-2b0707bda62f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>mode_edit</value>
      <webElementGuid>b9de49b6-84e3-4208-bdf0-b049a1c716bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[1]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row&quot;]/div[2]/div[@class=&quot;col-xs-12 col-sm-12 col-md-10 col-lg-10&quot;]/div[@class=&quot;container-fluid&quot;]/div[2]/div[@class=&quot;row panel panel-default&quot;]/div[@class=&quot;list-group-item&quot;]/h4[@class=&quot;list-group-item-heading&quot;]/button[@class=&quot;btn btn-primary-dk pull-right&quot;]/i[@class=&quot;material-icons pull-right thumbster-button-icon&quot;]</value>
      <webElementGuid>4a358c5c-a956-4850-bfac-cec9c01d58b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div[2]/div[2]/div/div[2]/div/div[2]/h4/button/i</value>
      <webElementGuid>3e659fcb-2a8a-440d-be44-9b7157955c04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit Site Type'])[2]/following::i[1]</value>
      <webElementGuid>394e1310-c5da-4092-ade0-3fbd79e6ea87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/h4/button/i</value>
      <webElementGuid>8bc62868-f982-4f43-9237-14f87087e70d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[(text() = 'mode_edit' or . = 'mode_edit')]</value>
      <webElementGuid>86ae0b42-f019-462d-be53-a7f90361f5b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
