import static com.kms.katalon.core.checkpoint.CheckpointFactory.findCheckpoint
import static com.kms.katalon.core.testcase.TestCaseFactory.findTestCase
import static com.kms.katalon.core.testdata.TestDataFactory.findTestData
import static com.kms.katalon.core.testobject.ObjectRepository.findTestObject
import static com.kms.katalon.core.testobject.ObjectRepository.findWindowsObject
import com.kms.katalon.core.checkpoint.Checkpoint as Checkpoint
import com.kms.katalon.core.cucumber.keyword.CucumberBuiltinKeywords as CucumberKW
import com.kms.katalon.core.mobile.keyword.MobileBuiltInKeywords as Mobile
import com.kms.katalon.core.model.FailureHandling as FailureHandling
import com.kms.katalon.core.testcase.TestCase as TestCase
import com.kms.katalon.core.testdata.TestData as TestData
import com.kms.katalon.core.testng.keyword.TestNGBuiltinKeywords as TestNGKW
import com.kms.katalon.core.testobject.TestObject as TestObject
import com.kms.katalon.core.webservice.keyword.WSBuiltInKeywords as WS
import com.kms.katalon.core.webui.keyword.WebUiBuiltInKeywords as WebUI
import com.kms.katalon.core.windows.keyword.WindowsBuiltinKeywords as Windows
import internal.GlobalVariable as GlobalVariable
import org.openqa.selenium.Keys as Keys

//driver = new ChromeDriver();
WebUI.openBrowser('')

WebUI.navigateToUrl('https://staging-web-app.ratio.city/login')

WebUI.click(findTestObject('Object Repository/Ratio.city/Page_Ratio.City Platform/button_Login'))

//driver.wait(20)
// driver.manage().timeouts().implicitlyWait(60, TimeUnit.SECONDS);
WebUI.delay(20, FailureHandling.STOP_ON_FAILURE)

WebUI.setText(findTestObject('Object Repository/Issue/Page_Sign In with Auth0/input_Ratio.City_email'), 'barty@example.com')

WebUI.waitForElementPresent(findTestObject('Object Repository/Issue/Page_Sign In with Auth0/input_Ratio.City_password'), 
    20)

WebUI.setEncryptedText(findTestObject('Object Repository/Issue/Page_Sign In with Auth0/input_Ratio.City_password'), 'wk79G5UFYJYwfJuHF1SqsetS8PD2KDH+')

WebUI.click(findTestObject('Object Repository/Issue/Page_Sign In with Auth0/span'))

WebUI.navigateToUrl('https://staging-web-app.ratio.city/login/callback#access_token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik16ZzRRMFJFUkRsQ05qWXdPVEpFT1RoRk5VTkJOamMwTnprMlJVSTJNRFJDTkRKQlF6TkJNQSJ9.eyJpc3MiOiJodHRwczovL3JhdGlvY2l0eS5hdXRoMC5jb20vIiwic3ViIjoiYXV0aDB8NjA4MTkxNWY3NTMyZmQwMDY4NjBlODYyIiwiYXVkIjpbImh0dHBzOi8vYXBpLnRvb2xzLnJhdGlvLmNpdHkiLCJodHRwczovL3JhdGlvY2l0eS5hdXRoMC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNjg1MDAwMjgxLCJleHAiOjE2ODUwMjkwODEsImF6cCI6IlFLSUE3eTRkanhFWVE0MHpiNmZIRkszQ0M4ZHFDOFVmIiwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBlbWFpbCJ9.QmcMBJ0Ixh316Ezk3VpxuU5p7jFI8ma3d_bIPbuY6yyBiXkqe9UFkpAVRfUoCW7i568o445Ve_ivHxl41hwiomg_ie19HhiQWx8DuwLW73tcj-ht7Aatz5iV9ZGvECEMnqoszVxMTp0_P4iTdxJLUXUWcuqxREYjtpGddCR9WwrL4Omt31MPAKHpNjuExcFKmzgsFSq00zWp9zqrsSQTo-JJ5mm9dREyj_D9oekXhPuv_yL8totxcOXKC-D0yeilDN6lzaadpQpEkG_zf5Yj1yDc2jLvHUnkzn4sbF4kp98XVP93qyXePSg6M56XC8f4EVO9uTgb9YBafPjZtnRjQQ&scope=openid%20profile%20email&expires_in=28800&token_type=Bearer&state=ZvtN0cql~f.f6BP.Eb1SZkbEKtgHgPx4&id_token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik16ZzRRMFJFUkRsQ05qWXdPVEpFT1RoRk5VTkJOamMwTnprMlJVSTJNRFJDTkRKQlF6TkJNQSJ9.eyJuaWNrbmFtZSI6ImJhcnR5IiwibmFtZSI6ImJhcnR5QGV4YW1wbGUuY29tIiwicGljdHVyZSI6Imh0dHBzOi8vcy5ncmF2YXRhci5jb20vYXZhdGFyLzY2NGFjZjMwOGM1NzM4NGNiYWZiNzhiYTVjNWY0YjdkP3M9NDgwJnI9cGcmZD1odHRwcyUzQSUyRiUyRmNkbi5hdXRoMC5jb20lMkZhdmF0YXJzJTJGYmEucG5nIiwidXBkYXRlZF9hdCI6IjIwMjMtMDUtMjVUMDc6Mzg6MDAuNjAzWiIsImVtYWlsIjoiYmFydHlAZXhhbXBsZS5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiaXNzIjoiaHR0cHM6Ly9yYXRpb2NpdHkuYXV0aDAuY29tLyIsImF1ZCI6IlFLSUE3eTRkanhFWVE0MHpiNmZIRkszQ0M4ZHFDOFVmIiwiaWF0IjoxNjg1MDAwMjgxLCJleHAiOjE2ODUwMjkwODEsInN1YiI6ImF1dGgwfDYwODE5MTVmNzUzMmZkMDA2ODYwZTg2MiIsImF0X2hhc2giOiJvWVpZcVNPRVhqTFdnMkt2T1JfVnpnIiwic2lkIjoiVXJGb2lfX1FmcDI1QTh0UEpSM0JZQkpsSzJ2dWRJVXoiLCJub25jZSI6Im11S2tzLV9Tc096Y3FNeTVkU2x5Lm1xS0xIeVhWRXNhIn0.qJAELxF8HGUwUBzwRF6LQGR8Nb0Gz-7NoPO6x2a3OvoGIUtcNyRK2upxeKOSkHCANwgJlnnOAX0aBeGv7fn81UNUTbXMYWHBEcfMS_c2JPK6fa9XIpYxjErJPTye2fm-DEvcV65LYcKV5CUGTxV0q6VlmVadu5x0PKblTWkJPcKApn-bA4V0XmqWGAmMy87NcJtfTtbYtXM5Tg9gpbrXQnnOlNyCi-EHaCfi5hPyWQB8NzmdHJz66U4qMp5cH6dnyRmNIviB4jNQLQqjU5ebFaAJAIlvEJbQlcwmUaCX6VJtvbdIeDHZBeYYCoFzRCf0Dwnuyn7pB8OuFum9-QaakQ')

WebUI.click(findTestObject('Object Repository/Issue1/Page_Ratio.City Explore/span_Yes, restore view'))

WebUI.delay(30)

WebUI.click(findTestObject('Object Repository/Issue1/Page_Ratio.City Explore/button_search Locate'))

