<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_image-1</name>
   <tag></tag>
   <elementGuidId>95e70198-4442-48a5-9064-833436b89074</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field-click-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='field-click-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>65b30098-8d6e-42a0-a1e9-3895bc3b37ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-click-container</value>
      <webElementGuid>6da61d55-7b98-47ce-92a0-4dce9ef64ab2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>c9e39100-c354-44f7-89b5-7aca9813ac90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>contenteditable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>669cf00c-6590-4717-956d-383a8e6be0f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>renderer-mirata-forms-273 react-resizable</value>
      <webElementGuid>93829b7a-54a9-46aa-b398-cb4b9742c4f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>image-1</value>
      <webElementGuid>632f4c39-ed9d-4918-9036-2c0baf1d1471</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field-click-container&quot;)</value>
      <webElementGuid>c375d87b-8ae9-44a8-a3f8-4e685481144d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='field-click-container']</value>
      <webElementGuid>263ce0d8-81ab-4c0f-9e6c-92576d9d886d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='2hddV6b6fQSe4PradVk1gZ-presentation-dnd-wrapper-id']/div/div</value>
      <webElementGuid>f8ea7e30-cf17-40e6-8727-3becb8e48f00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='demo27'])[2]/following::div[3]</value>
      <webElementGuid>48412224-75b3-47b8-8391-2aa8d02a7d24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Opens a URL'])[1]/following::div[14]</value>
      <webElementGuid>18076549-3d17-40f4-ab8d-9f2e4ddadd58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show Hidden Fields'])[1]/preceding::div[24]</value>
      <webElementGuid>b51e0373-62b3-4f07-82b5-387c09aa88d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/div/div/div/div/div/div/div/div/div</value>
      <webElementGuid>a70c8f3e-f00e-42cd-879e-85efd5b037d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'field-click-container' and (text() = 'image-1' or . = 'image-1')]</value>
      <webElementGuid>536bbc2c-6ca0-48fc-9de0-a448164a6589</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
