<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Decimal</name>
   <tag></tag>
   <elementGuidId>cf826125-1479-4bcc-8494-545cbbccfd70</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/amplify-authenticator/div[2]/div/div[4]/div/div/div/div[2]/div[2]/div/div[4]/div[2]/div</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>IMAGE</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5ea69c58-7e8c-4523-8390-90c33bf8b2c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-controls-section-control-label</value>
      <webElementGuid>2d7a7b6f-a8fb-4c20-87dc-f17afa121cf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Decimal</value>
      <webElementGuid>b28d3229-2165-4b6f-81ca-d6f72ff6a411</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/amplify-authenticator[@class=&quot;hydrated&quot;]/div[@class=&quot;l-designer-wrapper&quot;]/div[@class=&quot;l-designer-grid&quot;]/div[@class=&quot;l-designer-panel-content left-dpc&quot;]/div[@class=&quot;c-panel-content&quot;]/div[1]/div[@class=&quot;control-selector-panel&quot;]/div[@class=&quot;control-selector-sections&quot;]/div[@class=&quot;a-controls-section&quot;]/div[@class=&quot;a-controls-section-body&quot;]/div[@class=&quot;a-controls-section-control&quot;]/div[@class=&quot;a-controls-section-control-text&quot;]/div[@class=&quot;a-controls-section-control-label&quot;]</value>
      <webElementGuid>7fd9a235-f3e3-46e8-93bf-b31298f7e3c0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/amplify-authenticator/div[2]/div/div[4]/div/div/div/div[2]/div[2]/div/div[4]/div[2]/div</value>
      <webElementGuid>9a3a4efd-42df-44d6-9a10-11284e032f2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Whole number data input'])[1]/following::div[4]</value>
      <webElementGuid>16b178aa-f46f-46d5-84d7-b5f956905d92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Number'])[1]/following::div[5]</value>
      <webElementGuid>a27d8e19-7208-4642-bb1b-9e745dbae1b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Decimal data input'])[1]/preceding::div[1]</value>
      <webElementGuid>37e88540-7720-4a05-bb5f-2a32fb8d427b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Checkbox'])[1]/preceding::div[3]</value>
      <webElementGuid>1a6e6a02-9221-408a-9bb1-7ed952f41199</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Decimal']/parent::*</value>
      <webElementGuid>9ec0d5c4-86d2-40fc-8839-0f2dd0583007</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[4]/div[2]/div</value>
      <webElementGuid>772b9af1-e13c-4d37-b2d0-5ef24b8f7e8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Decimal' or . = 'Decimal')]</value>
      <webElementGuid>5a55dad0-e727-40dd-9236-618d28abc7cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
