<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Toronto</name>
   <tag></tag>
   <elementGuidId>30142f99-ce49-4699-9a14-1f58cbe30c39</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.mat-focus-indicator.city-button.mat-button.mat-button-base.ng-star-inserted.cdk-focused.cdk-mouse-focused > span.mat-button-wrapper</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-sidenav-container[@id='app-area']/mat-sidenav/div/div/div[2]/ratio-layer-explorer/ratio-my-cities/button[10]/span</value>
      </entry>
      <entry>
         <key>IMAGE</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9b314632-9527-46b1-b2bf-a62f6df48777</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-button-wrapper</value>
      <webElementGuid>fa2c409e-cbe8-45ae-afb3-12f90e8b9c0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Toronto
</value>
      <webElementGuid>d070ef88-692e-49ec-95f5-193f665c9549</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app-area&quot;)/mat-sidenav[@class=&quot;mat-drawer mat-sidenav main-sidebar ng-tns-c186-4 ng-trigger ng-trigger-transform mat-drawer-side mat-drawer-opened ng-star-inserted&quot;]/div[@class=&quot;mat-drawer-inner-container ng-tns-c186-4&quot;]/div[@class=&quot;ng-tns-c186-4&quot;]/div[@class=&quot;ng-star-inserted&quot;]/ratio-layer-explorer[@class=&quot;ng-star-inserted&quot;]/ratio-my-cities[@class=&quot;ng-star-inserted&quot;]/button[@class=&quot;mat-focus-indicator city-button mat-button mat-button-base ng-star-inserted cdk-focused cdk-mouse-focused&quot;]/span[@class=&quot;mat-button-wrapper&quot;]</value>
      <webElementGuid>4277c05b-20f0-40a4-8ed4-4d9ccefd5aa5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-sidenav-container[@id='app-area']/mat-sidenav/div/div/div[2]/ratio-layer-explorer/ratio-my-cities/button[10]/span</value>
      <webElementGuid>8c59ff7e-2dbc-4362-a826-9f168d13e006</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Richmond Hill'])[1]/following::span[3]</value>
      <webElementGuid>be95c521-9501-4d4f-8c54-beb016fecd80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pickering'])[1]/following::span[6]</value>
      <webElementGuid>8b308e78-0031-4a2f-98b6-6b0d4173ed0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vaughan'])[1]/preceding::span[3]</value>
      <webElementGuid>2cde318d-38fd-4858-9807-1b59ee2da80d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Waterloo'])[1]/preceding::span[6]</value>
      <webElementGuid>82422a68-6421-4750-82fa-3cf2d409a0e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Toronto']/parent::*</value>
      <webElementGuid>270fefce-dd79-46fb-a1b1-9c550a87d4cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[10]/span</value>
      <webElementGuid>f44b9fc7-2adb-471e-be1e-28d220086776</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' Toronto
' or . = ' Toronto
')]</value>
      <webElementGuid>9bbb050e-7c78-4bcd-8a84-46132084422c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
