<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_username</name>
   <tag></tag>
   <elementGuidId>947a76bd-4f2a-4d91-a975-d85d1d149b92</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='signInFormUsername'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a277b412-a775-40bd-88b5-e62e158ce5fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>signInFormUsername</value>
      <webElementGuid>c020e9bc-8dfc-4f75-90ea-9607436fb369</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>4d9d527f-dbe0-431c-9167-755e75e5ff7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c3fc64bd-b085-4c64-8dc7-bd74cc3e669e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control inputField-customizable</value>
      <webElementGuid>e36130b0-106d-41bd-b5be-30da3fec7f78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>name@host.com</value>
      <webElementGuid>1e07870c-6ca0-4185-baf0-177272263cf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>5f8d957c-a620-4d83-a2ef-ec52ff2efc14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;a-js a-audio a-video a-canvas a-svg a-drag-drop a-geolocation a-history a-webworker a-autofocus a-input-placeholder a-textarea-placeholder a-local-storage a-gradients a-hires a-transform3d a-touch-scrolling a-text-shadow a-text-stroke a-box-shadow a-border-radius a-border-image a-opacity a-transform a-transition&quot;]/body[1]/div[@class=&quot;container&quot;]/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content background-customizable modal-content-desktop visible-md visible-lg&quot;]/div[@class=&quot;modal-body&quot;]/div[2]/div[@class=&quot;panel panel-left-border col-md-6 col-lg-6&quot;]/div[2]/div[1]/form[@class=&quot;cognito-asf&quot;]/div[1]/input[@id=&quot;signInFormUsername&quot;]</value>
      <webElementGuid>4292efe0-fa8e-401d-b79c-6c77a5edb3e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='signInFormUsername'])[2]</value>
      <webElementGuid>0be23628-3c65-4b1e-bc5d-13c3c037698b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/form/div/input</value>
      <webElementGuid>9ebb335b-132f-4dd7-95a6-6868f13fb00e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'signInFormUsername' and @name = 'username' and @type = 'text' and @placeholder = 'name@host.com']</value>
      <webElementGuid>0e054b12-ff0b-45ba-a8da-e963c864f671</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
