<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_grid_474636511_0_header_table_RegionId</name>
   <tag></tag>
   <elementGuidId>b3589fd7-f6c5-4037-8eb6-485141cd0f08</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#grid_474636511_0RegionId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='grid_474636511_0RegionId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9a121b63-1407-4ea9-bd94-7a06fe910fe8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>e-field e-input e-defaultcell e-control e-textbox e-lib</value>
      <webElementGuid>f0aa978a-6df3-452e-9047-554db8c27971</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>74865939-d520-4ed3-ae8f-71699c5fda98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>grid_474636511_0RegionId</value>
      <webElementGuid>e6bb5f40-365b-477f-a55a-9e724b518a31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>RegionId</value>
      <webElementGuid>4b6b2b82-0368-4dec-bcb3-1b03224c6760</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>e-mappinguid</name>
      <type>Main</type>
      <value>grid-column2</value>
      <webElementGuid>34ab83d8-f944-4911-9696-a9166154fd11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>e19bc17b-9087-4366-92f0-070b0c792feb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;grid_474636511_0RegionId&quot;)</value>
      <webElementGuid>8c1135ca-7d4b-41f4-84f7-51869ef77146</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='grid_474636511_0RegionId']</value>
      <webElementGuid>9625919d-fa51-48a6-a948-1647a88450d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='grid_474636511_0EditForm']/table/tbody/tr/td[3]/span/input</value>
      <webElementGuid>cb80ef05-41d3-42d8-a5aa-fa5ec3173bd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/span/input</value>
      <webElementGuid>fcb94adf-cf02-4d39-aac3-ea65daf02cfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'grid_474636511_0RegionId' and @name = 'RegionId']</value>
      <webElementGuid>b6e225f0-7e4e-450a-bfcd-0475347901b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
