<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>body_You need to enable JavaScript to run t_dfa71a_1</name>
   <tag></tag>
   <elementGuidId>abca2775-24c9-447b-a49f-3a22fe0a5dd5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>body</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>body</value>
      <webElementGuid>c1211b21-ec29-44ab-8a0d-0b3d8ccb046b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>You need to enable JavaScript to run this app.Mirata Forms DesignerClick to Sign In© Mirata Software LLC | 2023qa | 2.2.1 (9959) | 10-June-2023Kavita BhattMirata DesignerOpen RecentAppend Standard comments dropdown to Comments fieldSat May 13 20231abcdrainTue Apr 18 2023FormsWorkflowsTemplatesCreateNameModifiedUpdated byVersion1abcdrainTue Apr 18 202310Append Standard comments dropdown to Comments fieldSat May 13 20233© Mirata Software LLC | 2023qa | 2.2.1 (9959) | 10-June-2023id(&quot;menu-&quot;)/div[1]FormTemplateNew FormBlankFrom ExistingType *​Name *DescriptionID *Workflow ID *CancelOKacme-id.form-type.drainsacme-id.form-type.plugs</value>
      <webElementGuid>6d95861c-23b5-4eb4-8ea1-f835f85bd531</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;hydrated&quot;]/body[1]</value>
      <webElementGuid>8fa6c07a-5bc3-4282-97fb-f2d72cd255e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body</value>
      <webElementGuid>4592be3f-ca21-476a-8c31-5f6b7c256619</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//body[(text() = 'You need to enable JavaScript to run this app.Mirata Forms DesignerClick to Sign In© Mirata Software LLC | 2023qa | 2.2.1 (9959) | 10-June-2023Kavita BhattMirata DesignerOpen RecentAppend Standard comments dropdown to Comments fieldSat May 13 20231abcdrainTue Apr 18 2023FormsWorkflowsTemplatesCreateNameModifiedUpdated byVersion1abcdrainTue Apr 18 202310Append Standard comments dropdown to Comments fieldSat May 13 20233© Mirata Software LLC | 2023qa | 2.2.1 (9959) | 10-June-2023id(&quot;menu-&quot;)/div[1]FormTemplateNew FormBlankFrom ExistingType *​Name *DescriptionID *Workflow ID *CancelOKacme-id.form-type.drainsacme-id.form-type.plugs' or . = 'You need to enable JavaScript to run this app.Mirata Forms DesignerClick to Sign In© Mirata Software LLC | 2023qa | 2.2.1 (9959) | 10-June-2023Kavita BhattMirata DesignerOpen RecentAppend Standard comments dropdown to Comments fieldSat May 13 20231abcdrainTue Apr 18 2023FormsWorkflowsTemplatesCreateNameModifiedUpdated byVersion1abcdrainTue Apr 18 202310Append Standard comments dropdown to Comments fieldSat May 13 20233© Mirata Software LLC | 2023qa | 2.2.1 (9959) | 10-June-2023id(&quot;menu-&quot;)/div[1]FormTemplateNew FormBlankFrom ExistingType *​Name *DescriptionID *Workflow ID *CancelOKacme-id.form-type.drainsacme-id.form-type.plugs')]</value>
      <webElementGuid>a1b9765c-4f7c-402d-867f-a36f061b6b7a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
