<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_image</name>
   <tag></tag>
   <elementGuidId>55753c9e-8d05-4dec-9dcc-f07fb072b4b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;root&quot;]/amplify-authenticator/div[2]/div/div[4]/div/div/div/div[2]/div[5]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6709b9fa-f794-41df-85df-7fdd85055428</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-controls-section-control-label</value>
      <webElementGuid>d03f9c97-1f47-4ca9-8105-bacfe771a7ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>301f4ab2-13b5-4370-9421-9eb4a9251850</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/amplify-authenticator[@class=&quot;hydrated&quot;]/div[@class=&quot;l-designer-wrapper&quot;]/div[@class=&quot;l-designer-grid&quot;]/div[@class=&quot;l-designer-panel-content left-dpc&quot;]/div[@class=&quot;c-panel-content&quot;]/div[1]/div[@class=&quot;control-selector-panel&quot;]/div[@class=&quot;control-selector-sections&quot;]/div[@class=&quot;a-controls-section&quot;]/div[@class=&quot;a-controls-section-body&quot;]/div[@class=&quot;a-controls-section-control&quot;]/div[@class=&quot;a-controls-section-control-text&quot;]/div[@class=&quot;a-controls-section-control-label&quot;]</value>
      <webElementGuid>048fbeda-6c2d-420f-93d7-a58caa389472</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/amplify-authenticator/div[2]/div/div[4]/div/div/div/div[2]/div[5]/div/div/div[2]/div</value>
      <webElementGuid>efaa58c8-ce32-4686-8804-03cdf990c13f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='images &amp; media'])[1]/following::div[7]</value>
      <webElementGuid>1c48379c-1349-4104-90a1-f535f15a58f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='data groupings'])[1]/following::div[11]</value>
      <webElementGuid>49401b39-63a9-4450-8265-e8e8cd6ee295</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='image'])[2]/preceding::div[1]</value>
      <webElementGuid>da46f58e-8697-4c85-9c59-c138bb03c75f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Display, capture or upload an image'])[1]/preceding::div[2]</value>
      <webElementGuid>b13fd16a-9997-433a-ac5e-c3b3d87d38e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='image']/parent::*</value>
      <webElementGuid>44a19965-adc0-419a-93c6-e5f423e2ff28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div[2]/div</value>
      <webElementGuid>0dfa5d30-7acf-40bd-a834-053bfb886439</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'image' or . = 'image')]</value>
      <webElementGuid>3f6498db-dbfa-4723-8eed-cc1903cb952f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
