<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_acme-id.form-type.drains</name>
   <tag></tag>
   <elementGuidId>e04111e7-f24d-4ad2-a936-d5fa94c8efb8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='menu-']/div[3]/ul/li</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu- > div.renderer-MuiPaper-root.renderer-MuiMenu-paper.renderer-MuiPopover-paper.renderer-MuiPaper-elevation8.renderer-MuiPaper-rounded > ul.renderer-MuiList-root.renderer-MuiMenu-list.renderer-MuiList-padding > li.renderer-MuiButtonBase-root.renderer-MuiListItem-root.renderer-MuiMenuItem-root.renderer-MuiMenuItem-gutters.renderer-MuiListItem-gutters.renderer-MuiListItem-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>2c756bc5-4147-4c1c-b2d3-ad3e08032bd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>renderer-MuiButtonBase-root renderer-MuiListItem-root renderer-MuiMenuItem-root renderer-MuiMenuItem-gutters renderer-MuiListItem-gutters renderer-MuiListItem-button</value>
      <webElementGuid>1c187769-cedc-4b7c-ba6a-5d80020289d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1d975b38-d4fa-40a4-a33a-c2a1f1f22f9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>2a12d404-b130-498c-9d4e-eff4f47c613f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9701f376-195a-44da-9a7c-83823ca893b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>acme-id.form-type.drains</value>
      <webElementGuid>6892957b-32da-4b01-9fb9-de78aa172dbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>acme-id.form-type.drains</value>
      <webElementGuid>82ae5aa4-793c-4744-b422-81df65194133</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-&quot;)/div[@class=&quot;renderer-MuiPaper-root renderer-MuiMenu-paper renderer-MuiPopover-paper renderer-MuiPaper-elevation8 renderer-MuiPaper-rounded&quot;]/ul[@class=&quot;renderer-MuiList-root renderer-MuiMenu-list renderer-MuiList-padding&quot;]/li[@class=&quot;renderer-MuiButtonBase-root renderer-MuiListItem-root renderer-MuiMenuItem-root renderer-MuiMenuItem-gutters renderer-MuiListItem-gutters renderer-MuiListItem-button&quot;]</value>
      <webElementGuid>653d5d04-e286-488a-bd33-dce1a9048c3c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu-']/div[3]/ul/li</value>
      <webElementGuid>981185f5-2ba0-41a2-ba6e-17fae57279db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OK'])[1]/following::li[1]</value>
      <webElementGuid>374b3fb2-d012-4071-970f-82d514743122</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::li[1]</value>
      <webElementGuid>414e01c0-3ff0-4b15-94e2-9aeb1fb0f5aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='acme-id.form-type.plugs'])[1]/preceding::li[1]</value>
      <webElementGuid>42cbe1dd-8f1b-4686-9c84-559230c11a7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='acme-id.form-type.drains']/parent::*</value>
      <webElementGuid>093cbfa3-1000-42b4-ba0b-cd07f5f1040f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[3]/ul/li</value>
      <webElementGuid>fb9cfa00-6971-4cb7-bec6-8098e37209fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'acme-id.form-type.drains' or . = 'acme-id.form-type.drains')]</value>
      <webElementGuid>ba1ae2a1-81eb-43e0-b191-fefbccf2833b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
