<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Ratio.City_password</name>
   <tag></tag>
   <elementGuidId>f1ef21ff-0c2f-4fbf-ac64-93064a49859a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;password&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1f89e322-db30-4bc3-9c25-06a8eae2cfc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>d8306312-1bc3-4223-bb99-d900d6a197a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>edaf5dfd-77fd-45a9-a3b6-3116bd638ee8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>auth0-lock-input</value>
      <webElementGuid>bc477bad-df66-4486-a421-6a8c2acab408</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>6be9f9b8-0365-4364-a19f-869a746bae08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>db06e1fb-758c-4f26-8e43-42f410ef320a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>your password</value>
      <webElementGuid>a66673c9-42d5-48d9-91eb-c3533c539175</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;auth0-lock-container-1&quot;)/div[@class=&quot;auth0-lock auth0-lock-opened&quot;]/div[@class=&quot;auth0-lock-center&quot;]/form[@class=&quot;auth0-lock-widget&quot;]/div[@class=&quot;auth0-lock-widget-container&quot;]/div[@class=&quot;auth0-lock-cred-pane auth0-lock-quiet&quot;]/div[3]/span[1]/div[1]/div[1]/div[@class=&quot;auth0-lock-view-content&quot;]/div[1]/div[@class=&quot;auth0-lock-body-content&quot;]/div[@class=&quot;auth0-lock-content&quot;]/div[@class=&quot;auth0-lock-form&quot;]/div[1]/div[1]/div[@class=&quot;auth0-lock-input-block auth0-lock-input-show-password&quot;]/div[@class=&quot;auth0-lock-input-block auth0-lock-input-password&quot;]/div[@class=&quot;auth0-lock-input-wrap auth0-lock-focused auth0-lock-input-wrap-with-icon&quot;]/input[@class=&quot;auth0-lock-input&quot;]</value>
      <webElementGuid>bcafba75-8368-4bf5-b0e5-63449dbb01ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='password']</value>
      <webElementGuid>d649d1ba-f0f2-418f-b412-84c998844e99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='auth0-lock-container-1']/div/div[2]/form/div/div/div[3]/span/div/div/div/div/div/div/div/div/div/div[2]/div/div/input</value>
      <webElementGuid>8c74b05b-1319-4fc6-83f6-99201a3927e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>275d8d79-0474-4f5e-948f-6c8235406430</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'password' and @placeholder = 'your password']</value>
      <webElementGuid>78dbf443-0fda-43e7-a503-de3bbc959840</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
