<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select LanguageArabicChinese_Mandari_d78a49</name>
   <tag></tag>
   <elementGuidId>e301e4ab-0952-4a9d-b6ab-17bf7b1af863</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//select[@id='cars'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>609e7725-df87-4809-9bba-1c5bf469f79d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cars</value>
      <webElementGuid>1c560e3f-1965-4892-a3f6-4c9c1b8fca36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>languageCode</value>
      <webElementGuid>bac4ee99-c0e2-42e9-b6cf-bedaa003cb36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
												Select Language
												Arabic
												Chinese_Mandarin
												Danish
												Dutch
												English_Australian
												English_British
												English_Indian
												English_New_Zealand
												English_South_African
												English_US
												English_Welsh
												French
												French_Canadian
												Hindi
												German
												Icelandic
												Italian
												Japanese
												Korean
												Norwegian
												Polish
												Portuguese_Brazilian
												Portuguese_European
												Romanian
												Russian
												Spanish_European
												Spanish_Mexican
												Spanish_US
												Swedish
												Turkish
												Welsh
										</value>
      <webElementGuid>eba20057-2ab0-4450-9200-98927cc3a8d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;js flexbox canvas canvastext webgl no-touch geolocation postmessage websqldatabase indexeddb hashchange history draganddrop websockets rgba hsla multiplebgs backgroundsize borderimage borderradius boxshadow textshadow opacity cssanimations csscolumns cssgradients cssreflections csstransforms csstransforms3d csstransitions fontface generatedcontent video audio localstorage sessionstorage webworkers no-applicationcache svg inlinesvg smil svgclippaths&quot;]/body[1]/div[@class=&quot;wrapper&quot;]/section[2]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/table[@class=&quot;table table-striped table-condensed&quot;]/tbody[1]/tr[@class=&quot;main-table&quot;]/td[4]/select[@id=&quot;cars&quot;]</value>
      <webElementGuid>9bec74b5-6c58-4ef3-8c78-c94862b2c7b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//select[@id='cars'])[3]</value>
      <webElementGuid>dc20481c-a149-4d70-af0a-aa70fc1c093b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage Files'])[1]/following::select[3]</value>
      <webElementGuid>b2846421-0c5f-4619-8f5b-58933ae1d315</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download the file to your computer.'])[1]/following::select[3]</value>
      <webElementGuid>4a9011f6-a46b-45f8-9810-61c58cf467c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload'])[1]/preceding::select[1]</value>
      <webElementGuid>94a93ba1-8257-4a6b-b21e-954f3e6dc333</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Us'])[2]/preceding::select[1]</value>
      <webElementGuid>7e4ae1bc-6317-46ab-aab1-5098a522d869</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/select</value>
      <webElementGuid>1273c880-82ff-41b0-a2e6-c2e9446cbf22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cars' and @name = 'languageCode' and (text() = '
												Select Language
												Arabic
												Chinese_Mandarin
												Danish
												Dutch
												English_Australian
												English_British
												English_Indian
												English_New_Zealand
												English_South_African
												English_US
												English_Welsh
												French
												French_Canadian
												Hindi
												German
												Icelandic
												Italian
												Japanese
												Korean
												Norwegian
												Polish
												Portuguese_Brazilian
												Portuguese_European
												Romanian
												Russian
												Spanish_European
												Spanish_Mexican
												Spanish_US
												Swedish
												Turkish
												Welsh
										' or . = '
												Select Language
												Arabic
												Chinese_Mandarin
												Danish
												Dutch
												English_Australian
												English_British
												English_Indian
												English_New_Zealand
												English_South_African
												English_US
												English_Welsh
												French
												French_Canadian
												Hindi
												German
												Icelandic
												Italian
												Japanese
												Korean
												Norwegian
												Polish
												Portuguese_Brazilian
												Portuguese_European
												Romanian
												Russian
												Spanish_European
												Spanish_Mexican
												Spanish_US
												Swedish
												Turkish
												Welsh
										')]</value>
      <webElementGuid>26ff654e-c274-467f-a7e4-a784f0f0cca4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
