<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Quantity_atc-quantity</name>
   <tag></tag>
   <elementGuidId>1b421d8a-42ac-4acc-b66f-f5855d77d336</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#atc-quantity</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='atc-quantity']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>93f4ace6-ea78-4c5c-ba3e-150abdf9dba4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>b588a29d-c0e6-40e8-a8ab-1983683c6097</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>atc-quantity</value>
      <webElementGuid>75fb2b59-3b88-4cd2-858e-951422c2a0be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>atc-quantity</value>
      <webElementGuid>0875ae5a-d27e-465d-b7f5-1d36ba1d3c82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>d4a09d0d-3c2d-42e6-a127-bb48dc93252c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>50aadf2b-9534-42db-9023-bb3995dbfc20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>19a883d6-80f1-432e-918d-95e2e2052558</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>no-spinner w-7 md:w-full text-center border flex-grow rounded-l px-1 text-gray-500 text-xs focus-visible</value>
      <webElementGuid>d8759041-4e01-420f-b36b-d286b2a57819</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;atc-quantity&quot;)</value>
      <webElementGuid>9876a308-adc4-488a-9c9e-6a90b174c3df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='atc-quantity']</value>
      <webElementGuid>9de154c3-7915-4093-8204-811527ad4b70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shopify-section-product-main']/rec-product/div/div[2]/div[2]/div/div/div[10]/div/div/div/input</value>
      <webElementGuid>d6d07937-a1ca-4706-a39c-9fc9ee94e539</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/div/input</value>
      <webElementGuid>ab1c2653-af4b-4d54-bf1d-cd4f7a172bb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'atc-quantity' and @name = 'atc-quantity']</value>
      <webElementGuid>3f0a48c7-f927-47fa-bfb7-34fe9f0b1784</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
