<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_Quantity_fa-icon</name>
   <tag></tag>
   <elementGuidId>b2bc2144-84b7-47d2-931f-8d512e57c16f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Quantity'])[1]/following::*[name()='svg'][3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>722cb158-dc4c-4633-be46-a18ba53a1e10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>2bfcaaa3-6efa-4447-8890-66046d027e43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>414b7198-593f-411d-b6c0-cbb37ebc5f4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>b9c3e805-ffd9-4d1e-b0ff-6aad7c02e1be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>b075a429-6b50-48f8-8381-dc639e5fc054</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 24 24</value>
      <webElementGuid>6b8c72fe-7581-4805-be8e-b3bed14b0cc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>focusable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9046849c-ac3a-4b68-b5a2-396806c14db1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa-icon</value>
      <webElementGuid>8bde4ef9-e862-4691-9678-13f8c796d625</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shopify-section-product-main&quot;)/rec-product[1]/div[@class=&quot;pdp container&quot;]/div[@class=&quot;pdp__main grid grid-cols-12 gap-y-7 md:gap-x-12 pt-3.5 md:pt-0&quot;]/div[@class=&quot;pdp__main-sidebar col-span-12 md:col-span-6 false&quot;]/div[@class=&quot;inner-wrapper-sticky&quot;]/div[@class=&quot;flex flex-col&quot;]/div[@class=&quot;pdp__cart bg-white grid grid-cols-12 gap-4 py-5 border-t border-b border-gray-100&quot;]/div[@class=&quot;col-span-12 flex space-x-2&quot;]/div[@class=&quot;pdp__quantity text-center contains-price contains-transaction&quot;]/div[@class=&quot;flex border-gray-200&quot;]/div[@class=&quot;grid grid-rows-2&quot;]/button[@class=&quot;px-1 flex align-middle border border-l-0 border-t-0 bg-gray-50 rounded-br text-brand-500 md:px-2&quot;]/svg[@class=&quot;fa-icon&quot;]</value>
      <webElementGuid>0a53e1db-e9a1-4c4d-bc27-a3c97996b0af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quantity'])[1]/following::*[name()='svg'][3]</value>
      <webElementGuid>4debff0c-8202-4980-8fb4-7abff8dd04a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('What', &quot;'&quot;, 's Included')])[1]/following::*[name()='svg'][3]</value>
      <webElementGuid>717d2b00-8f36-4d45-93d8-18fbea6b4437</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add to wishlist'])[1]/preceding::*[name()='svg'][3]</value>
      <webElementGuid>8d2ddefb-fd11-4a2d-ab36-62632c047e05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add to cart'])[1]/preceding::*[name()='svg'][5]</value>
      <webElementGuid>ac4f820b-6035-4bf8-b425-c3f70040d347</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
