<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_2,519.98</name>
   <tag></tag>
   <elementGuidId>61406432-681d-44c8-93c9-6e3aa61cf66d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.el-tooltip.text-gray-700.font-semibold.w-max-content.text-base.focusing</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='cart-items']/div[2]/div/div/div/div/div/div[2]/div/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c156684e-340c-4696-88f5-c02b850e1f35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-tooltip text-gray-700 font-semibold w-max-content text-base focusing</value>
      <webElementGuid>cea3558f-d6cb-49de-814d-d5f8978a3111</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>el-tooltip-6679</value>
      <webElementGuid>4027097c-3261-43cc-8af5-11094e71ada9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>61dd48c8-6986-444d-8608-668de9f2c337</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
              $2,519.98
            </value>
      <webElementGuid>a8b36474-141c-4ff5-a910-40001bde128b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cart-items&quot;)/div[2]/div[1]/div[@class=&quot;space-y-8&quot;]/div[@class=&quot;bg-white rounded shadow-small-xs overflow-hidden divide-y divide-gray-200 border border-gray-200&quot;]/div[@class=&quot;cart-product&quot;]/div[@class=&quot;flex flex-col sm:flex-row sm:items-stretch justify-between&quot;]/div[@class=&quot;contains-price price-detail-section p-4 pt-0 sm:pt-4 md:p-6 w-full sm:w-4/12 lg:w-3/12&quot;]/div[@class=&quot;ml-28 sm:ml-0 text-right pr-2 md:pr-3 pt-0 md:pb-2 h-full flex flex-row flex-wrap items-center sm:flex-col sm:items-end sm:space-y-4 justify-between price-detail-section-margin&quot;]/div[@class=&quot;flex items-center space-x-3.5 sm:space-x-2 sm:flex-col sm:gap-y-1&quot;]/div[@class=&quot;el-tooltip text-gray-700 font-semibold w-max-content text-base focusing&quot;]</value>
      <webElementGuid>6af6ff84-8dc3-45c7-9879-7fc3ca6a7b67</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='cart-items']/div[2]/div/div/div/div/div/div[2]/div/div[2]/div</value>
      <webElementGuid>22de2dca-d9c9-42ce-97c6-3176fc281d8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$2,519.98'])[1]/following::div[2]</value>
      <webElementGuid>a4ecd0bd-2521-4439-b209-888cfd277ef8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quantity'])[1]/following::div[5]</value>
      <webElementGuid>e1f717e2-a17f-47b8-9435-dfc570b576e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Indoor Furniture Protection (5 Years)'])[1]/preceding::div[2]</value>
      <webElementGuid>8d274934-1961-419a-9ae6-e5592a9b7842</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('What', &quot;'&quot;, 's Included')])[1]/preceding::div[3]</value>
      <webElementGuid>536a5379-3a97-44dc-b061-17c30c6a3b8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div[2]/div/div[2]/div</value>
      <webElementGuid>7c2f63c9-61ef-4a1e-aa2a-42cc1fd8f516</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '
              $2,519.98
            ' or . = '
              $2,519.98
            ')]</value>
      <webElementGuid>d8cae38a-9e92-4a41-969a-35082d57fb7b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
