<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Canada</name>
   <tag></tag>
   <elementGuidId>bde27e58-fb6b-4b98-95c9-488e054f1cdd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='country-header-container']/ul/li/div/ul/li[2]/a</value>
      </entry>
      <entry>
         <key>IMAGE</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c73390c6-6af1-4c59-b4e0-66727753bcd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/en-ca</value>
      <webElementGuid>561b27b3-5572-46dd-9347-c8518b822900</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>text: name,
        events:
        {
            click: onSelectedMarketClick
        }</value>
      <webElementGuid>7465fe43-f688-4840-877c-2f5423256bdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Canada</value>
      <webElementGuid>ae437585-e2bf-40f7-acd0-1ad973da9ef5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;country-header-container&quot;)/ul[@class=&quot;header-country-and-language&quot;]/li[@class=&quot;country&quot;]/div[@class=&quot;show&quot;]/ul[@class=&quot;dropdown-menu culture-menu show&quot;]/li[2]/a[1]</value>
      <webElementGuid>be992962-b183-4ea7-be55-71f9a46d3c78</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='country-header-container']/ul/li/div/ul/li[2]/a</value>
      <webElementGuid>13e07013-aa94-45d4-94de-0ed5647640c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Canada')]</value>
      <webElementGuid>43bafc8b-4d83-4b91-8486-a8ecb2f57999</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='United States'])[3]/following::a[1]</value>
      <webElementGuid>52f1a13a-2261-4b3e-8b53-7c5af9a0a207</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='United States'])[2]/following::a[2]</value>
      <webElementGuid>3db3a836-e167-4bf2-8d93-2e98feca2e22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='United Kingdom'])[1]/preceding::a[1]</value>
      <webElementGuid>64c2e667-49c2-433d-9a1b-4ec830962723</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Republic of Ireland'])[1]/preceding::a[2]</value>
      <webElementGuid>4e612c4b-081f-47ab-84cd-41e872953eca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Canada']/parent::*</value>
      <webElementGuid>0f6551ab-9b74-43ad-af75-da8970dc8297</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/en-ca')]</value>
      <webElementGuid>e75479e7-66d4-4858-817b-c0fd84c6845e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a</value>
      <webElementGuid>694fd0a2-85e6-4b7e-843b-496907f67bc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/en-ca' and (text() = 'Canada' or . = 'Canada')]</value>
      <webElementGuid>3e97e158-237a-4272-98cf-b48c6a03ee76</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
