<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Region</name>
   <tag></tag>
   <elementGuidId>f6bf2a5b-1f30-44e4-96e5-1690e18ec8fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='sidenavAccordion']/div/div/div[5]/app-side-nav-item/nav/div/app-side-nav-item/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0d1b73f6-09dd-423d-ba50-ffd3bd8c35ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link</value>
      <webElementGuid>8afab8ce-d576-4d4a-9b57-1a5b1c332fc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Region </value>
      <webElementGuid>01148b30-f7ca-496b-b592-1dd8f0b43ea3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidenavAccordion&quot;)/div[@class=&quot;sidenav-menu&quot;]/div[@class=&quot;nav mt-3 mb-3&quot;]/div[@class=&quot;ng-star-inserted&quot;]/app-side-nav-item[@class=&quot;ng-star-inserted&quot;]/nav[@class=&quot;sidenav-menu-nested nav&quot;]/div[@class=&quot;ng-star-inserted&quot;]/app-side-nav-item[@class=&quot;submenu ng-star-inserted&quot;]/a[@class=&quot;nav-link&quot;]</value>
      <webElementGuid>150f447c-e426-43ba-a7a7-e3a04ae7ce81</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='sidenavAccordion']/div/div/div[5]/app-side-nav-item/nav/div/app-side-nav-item/a</value>
      <webElementGuid>15721332-e650-4384-bd98-f6b0620b149a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Region')]</value>
      <webElementGuid>78888d4c-89db-451c-9d04-76e25032ec11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Organization Admin'])[1]/following::a[1]</value>
      <webElementGuid>d45742fe-dbc8-4026-b95c-a6ecccf2d40e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Execute Contract'])[1]/following::a[2]</value>
      <webElementGuid>4cf7dc74-a6d8-40c3-ba8b-d97912f35bc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Location'])[1]/preceding::a[1]</value>
      <webElementGuid>a26ee21a-205a-44ad-b344-df86da24d2cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cost Center'])[1]/preceding::a[2]</value>
      <webElementGuid>940f9dbb-1b42-47fd-8091-290b08b563e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Region']/parent::*</value>
      <webElementGuid>0675241f-72f7-49f2-acbc-7e6d5c36bff2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/app-side-nav-item/nav/div/app-side-nav-item/a</value>
      <webElementGuid>5c0544cd-c74c-4950-97a8-10387503f87b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = ' Region ' or . = ' Region ')]</value>
      <webElementGuid>3cb45814-a4c8-4ec9-98c8-71f560d7137d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
