<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Code_code</name>
   <tag></tag>
   <elementGuidId>b35e1961-f591-4cf8-9b7b-9fccac69b505</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='forgot_password_code']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#forgot_password_code</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>089c36b0-20b9-4c22-b576-5cb23f76678a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>forgot_password_code</value>
      <webElementGuid>13137d07-500e-47de-86f0-73bc9358db81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control inputField-customizable</value>
      <webElementGuid>3126ee29-b888-4208-bc81-2250658f8c53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>b3904441-be94-4237-811d-36246da23573</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>code</value>
      <webElementGuid>1bd3d9ea-f146-4724-9255-af01dd94c35e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;forgot_password_code&quot;)</value>
      <webElementGuid>7cae134c-f638-4a8b-bdd6-b2c7f3f46990</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='forgot_password_code']</value>
      <webElementGuid>0ab5c8db-2b54-4cc9-9361-135e421e9e6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[5]</value>
      <webElementGuid>dcd8b36c-ba75-495a-8428-e3429803bd80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'forgot_password_code' and @type = 'password' and @name = 'code']</value>
      <webElementGuid>a9ee0a6b-f0e6-4a5b-a45d-496c9d87ee57</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
