<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Rating</name>
   <tag></tag>
   <elementGuidId>8b4e4e05-3e81-486c-bd62-59d8cc4e967b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='id-69']/section[2]/article/section/section/section/section/div[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c9301952-dd2e-42c4-a1bd-f05546bc0155</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ab67d689-c9c6-403d-8de1-647641fd571e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>6fe8c815-f14b-41f7-87e4-c40ac9cf6360</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-kDhYZr fckOLM</value>
      <webElementGuid>1a5a4527-351f-4ae9-bd6c-6192f5d202f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Rating</value>
      <webElementGuid>db6bf8c6-2c05-4469-bd01-350b2b4bc972</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;sc-13lc47p-0 hOPtIO&quot;]/div[@class=&quot;sc-re4bd0-6 kmkHCs modalWrapper&quot;]/div[@id=&quot;id-69&quot;]/section[@class=&quot;sc-re4bd0-11 fKQGZb&quot;]/article[@class=&quot;sc-ccLTTT huAiBP&quot;]/section[@class=&quot;sc-fCPvlr lhOusS&quot;]/section[@class=&quot;sc-1dm827j-0 jcZYcp&quot;]/section[@class=&quot;sc-1dm827j-1 dwEHGn&quot;]/section[@class=&quot;sc-1dm827j-4 feiKQi&quot;]/div[@class=&quot;sc-kDhYZr fckOLM&quot;]</value>
      <webElementGuid>104df94e-1744-4924-a1be-a0360e77fcbc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='id-69']/section[2]/article/section/section/section/section/div[3]</value>
      <webElementGuid>33e3c182-fc30-470c-adee-f39066b4c511</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filters'])[1]/following::div[4]</value>
      <webElementGuid>af597e6e-226c-430c-9b35-ab7548e087ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Social links'])[1]/following::div[23]</value>
      <webElementGuid>d263fb7a-dbf3-433f-ab55-e1483da4446f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search here'])[1]/preceding::div[6]</value>
      <webElementGuid>6dfce79c-f135-4a2f-aa61-a2b0486c179e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Afghan'])[1]/preceding::div[6]</value>
      <webElementGuid>9c8a8daf-b144-4817-a498-988d99ae4888</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/section/section/div[3]</value>
      <webElementGuid>291330b7-47a8-43fb-a02e-70af8ee7da6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Rating' or . = 'Rating')]</value>
      <webElementGuid>b8ec58bc-b2a5-4b6e-877d-19bfa1c20013</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
