<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Wraps_sc-1o2pknd-1 fZoyIB</name>
   <tag></tag>
   <elementGuidId>aa6b5a1f-55c4-4e31-9730-ba6d52c1b5e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='checkbox'])[113]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cf345a3f-99f9-4149-ab79-88779f397ff4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>52926187-e757-4a08-8253-3c8af408c848</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6c2330c4-9506-434b-9f44-ff4cd2296de2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>color</name>
      <type>Main</type>
      <value>#EF4F5F</value>
      <webElementGuid>c08ffe46-130c-4c95-b08b-b11a4457ee9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-1o2pknd-1 fZoyIB</value>
      <webElementGuid>e14e6580-21e0-4c28-a0c1-3ae6052577d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-fEUNkw gAkuDn&quot;]/div[@class=&quot;sc-bQNBTn hHgLCv&quot;]/div[@class=&quot;sc-1mo3ldo-0 fihUGr&quot;]/div[@class=&quot;sc-lSeQO gLkvUi&quot;]/div[@class=&quot;sc-lmuQER kghnYZ&quot;]/div[@class=&quot;sc-18n4g8v-0 gAhmYY&quot;]/div[@class=&quot;sc-cmIlrE rXScg&quot;]/div[@class=&quot;sc-gleUXh bSyqUv&quot;]/div[@class=&quot;sc-bhlBdH fFQRrn&quot;]/div[@class=&quot;sc-keFjpB fICbbc&quot;]/div[@class=&quot;sc-AnqlK bEcDhK&quot;]/label[@class=&quot;sc-1o2pknd-0 oQgkb&quot;]/input[@class=&quot;sc-1o2pknd-1 fZoyIB&quot;]</value>
      <webElementGuid>1a3ff351-c920-42b2-ab71-5adc2a6432a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='checkbox'])[113]</value>
      <webElementGuid>88be8c47-22d4-4be6-979b-15e6f5931bc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[5]/div/div/div[4]/div[2]/div/div/div/div/div[113]/label/input</value>
      <webElementGuid>64bbe09d-79d6-4357-b2ca-1d43dfde3efc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[113]/label/input</value>
      <webElementGuid>def41625-c553-463c-b8e4-e8245f5264ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>6a488130-e905-4caa-894b-60b2e4813bc0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
