<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Update</name>
   <tag></tag>
   <elementGuidId>9c88ffbb-4b97-4254-af01-ba081b8b477a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0de33d6e-e5eb-4b6c-9cbf-cc468b0ee770</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>a1020a84-371f-46e4-b3f0-7750711c38cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-postalcode-update bg-gray-800 text-xs text-white px-1 py-2 rounded hover:bg-gray-900 hover:text-white focus:text-white transition-colors ease-in-out duration-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-brand-300 disabled:opacity-30 disabled:cursor-not-allowed btn-ship-update</value>
      <webElementGuid>5a7f06bc-5bf1-4773-ab9d-59e062e8d2ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
      Update
    </value>
      <webElementGuid>3a51af1e-9f22-4c19-8358-d35208793e10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shopify-section-location-view-popup&quot;)/rec-location-popup[1]/div[@class=&quot;el-dialog__wrapper&quot;]/div[@class=&quot;el-dialog&quot;]/div[@class=&quot;el-dialog__body&quot;]/div[@class=&quot;flex flex-col space-y-3&quot;]/form[@class=&quot;grid grid-cols-3 lg:grid-cols-2 xl:grid-cols-3 gap-2 w-full&quot;]/button[@class=&quot;btn-postalcode-update bg-gray-800 text-xs text-white px-1 py-2 rounded hover:bg-gray-900 hover:text-white focus:text-white transition-colors ease-in-out duration-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-brand-300 disabled:opacity-30 disabled:cursor-not-allowed btn-ship-update&quot;]</value>
      <webElementGuid>bb87a7a0-8c4c-4572-8cd2-312fd74691b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>980fcad7-1db8-48a6-a3b4-09044cac1c51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shopify-section-location-view-popup']/rec-location-popup/div/div/div[2]/div[2]/form/button</value>
      <webElementGuid>83f09c3c-3860-4566-899e-27e984d941da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Update your postal code'])[1]/following::button[1]</value>
      <webElementGuid>db3bd8a3-466d-404c-ab9e-5c055999abd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Check your location'])[1]/following::button[3]</value>
      <webElementGuid>c4a1bd69-6088-40cc-ae06-0fca6ff87b82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please share your location for better pricing options.'])[1]/preceding::button[1]</value>
      <webElementGuid>adc1af77-0b3a-40fe-aea7-4f1dc39d722b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OR'])[1]/preceding::button[1]</value>
      <webElementGuid>0d1f4d19-e1e8-491d-b44d-b5e67408fec6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Update']/parent::*</value>
      <webElementGuid>8fcf607c-b3b7-40d6-83aa-1e99119d174d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/button</value>
      <webElementGuid>86c6727f-c013-4aad-90aa-1ea84b38e1b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = '
      Update
    ' or . = '
      Update
    ')]</value>
      <webElementGuid>7968ab68-f708-48c7-b610-6743b407411e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
