<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Kelowna, 2514 N Hwy 97_autosuggest__i_f230e2</name>
   <tag></tag>
   <elementGuidId>0db22b3e-1b48-4aa9-a223-6e5438924b61</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.autosuggest__input--open</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='search']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9ab3db86-c345-4861-9654-8894053ae276</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>387d35c2-bb3c-4250-8ae5-d96cb28d94ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>We furnish your dreams with a search</value>
      <webElementGuid>4d32e615-1c59-4f96-a5cb-d8e789376429</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>autosuggest__input--open</value>
      <webElementGuid>adc73cc8-2851-4ad5-81a2-ff6cabd9f395</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shopify-section-header-v3&quot;)/div[@class=&quot;header-v3&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;header__wrapper&quot;]/div[@class=&quot;header__col header__icons justify-end space-x-2 md:w-1/2&quot;]/div[@class=&quot;hidden lg:flex w-full h-full items-center&quot;]/rec-algolia-autocomplete[@class=&quot;ab_algolia_searchbar search-bar items-center mr-2 md:mr-4 w-full&quot;]/div[@class=&quot;input-search algolia-autocompate ais-InstantSearch&quot;]/div[@class=&quot;input-search algolia-autocompate ais-InstantSearch&quot;]/div[@class=&quot;ais-Autocomplete&quot;]/div[@id=&quot;autosuggest&quot;]/div[1]/div[@class=&quot;ais-SearchBox&quot;]/div[1]/input[@class=&quot;autosuggest__input--open&quot;]</value>
      <webElementGuid>10d9e784-cb15-4fa7-b855-ea31eeebaa3a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='search']</value>
      <webElementGuid>d7f48d55-022d-4ae1-b486-51dd958f1412</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='autosuggest']/div/div/div/input</value>
      <webElementGuid>3fe9820f-3228-44fd-8a1e-ab3a678e6270</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input</value>
      <webElementGuid>fe4c42c3-cef9-4b4f-b798-760b5818e82e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'search' and @placeholder = 'We furnish your dreams with a search']</value>
      <webElementGuid>17d38dc1-22d7-4726-bf50-0754ecee5379</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
