<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>body_You need to enable JavaScript to run t_0cee8e</name>
   <tag></tag>
   <elementGuidId>65cc59a3-92c1-4391-b854-2417bcfe70fc</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>body</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>IMAGE</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>body</value>
      <webElementGuid>35a967e2-344d-4bb8-87c1-64b16f04ec11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>You need to enable JavaScript to run this app.Mirata Forms DesignerClick to Sign In© Mirata Software LLC | 2023qa | 2.0.27 (9837) | 23-May-2023Kavita BhattMirata DesignerOpen Recent1A_Horses_MiniTue May 23 20231_HorsesWed Apr 19 20231MiniMon Apr 10 2023A_List_SigTue Mar 21 2023TL Test Email 012Tue Mar 14 2023FormsWorkflowsTemplatesCreateNameModifiedUpdated byVersion1_HorsesWed Apr 19 202371A_Horses_MiniTue May 23 202361GetGoodCookiesTue Mar 14 202331MiniMon Apr 10 20231A_List_SigTue Mar 21 20237TL Test Email 012Tue Mar 14 20231© Mirata Software LLC | 2023qa | 2.0.27 (9837) | 23-May-2023id(&quot;menu-&quot;)/div[@class=&quot;renderer-MuiPaper-root renderer-MuiMenu-paper renderer-MuiPopover-paper renderer-MuiPaper-elevation8 renderer-MuiPaper-rounded&quot;]/ul[@class=&quot;renderer-MuiList-root renderer-MuiMenu-list renderer-MuiList-padding&quot;]/li[@class=&quot;renderer-MuiButtonBase-root renderer-MuiListItem-root renderer-MuiMenuItem-root renderer-MuiMenuItem-gutters renderer-MuiListItem-gutters renderer-MuiListItem-button&quot;]FormTemplateNew FormBlankFrom ExistingType *​Name *DescriptionID *Workflow ID *CancelOKacme-id.form-type.terri-ype</value>
      <webElementGuid>6f996c17-a1de-418e-afc2-57177def7997</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;hydrated&quot;]/body[1]</value>
      <webElementGuid>139426d2-9b5e-440c-8e1a-d98a2ff7efc6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body</value>
      <webElementGuid>38cd9dd4-3e04-4ec4-b1c9-56ea2632a6b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//body[(text() = 'You need to enable JavaScript to run this app.Mirata Forms DesignerClick to Sign In© Mirata Software LLC | 2023qa | 2.0.27 (9837) | 23-May-2023Kavita BhattMirata DesignerOpen Recent1A_Horses_MiniTue May 23 20231_HorsesWed Apr 19 20231MiniMon Apr 10 2023A_List_SigTue Mar 21 2023TL Test Email 012Tue Mar 14 2023FormsWorkflowsTemplatesCreateNameModifiedUpdated byVersion1_HorsesWed Apr 19 202371A_Horses_MiniTue May 23 202361GetGoodCookiesTue Mar 14 202331MiniMon Apr 10 20231A_List_SigTue Mar 21 20237TL Test Email 012Tue Mar 14 20231© Mirata Software LLC | 2023qa | 2.0.27 (9837) | 23-May-2023id(&quot;menu-&quot;)/div[@class=&quot;renderer-MuiPaper-root renderer-MuiMenu-paper renderer-MuiPopover-paper renderer-MuiPaper-elevation8 renderer-MuiPaper-rounded&quot;]/ul[@class=&quot;renderer-MuiList-root renderer-MuiMenu-list renderer-MuiList-padding&quot;]/li[@class=&quot;renderer-MuiButtonBase-root renderer-MuiListItem-root renderer-MuiMenuItem-root renderer-MuiMenuItem-gutters renderer-MuiListItem-gutters renderer-MuiListItem-button&quot;]FormTemplateNew FormBlankFrom ExistingType *​Name *DescriptionID *Workflow ID *CancelOKacme-id.form-type.terri-ype' or . = 'You need to enable JavaScript to run this app.Mirata Forms DesignerClick to Sign In© Mirata Software LLC | 2023qa | 2.0.27 (9837) | 23-May-2023Kavita BhattMirata DesignerOpen Recent1A_Horses_MiniTue May 23 20231_HorsesWed Apr 19 20231MiniMon Apr 10 2023A_List_SigTue Mar 21 2023TL Test Email 012Tue Mar 14 2023FormsWorkflowsTemplatesCreateNameModifiedUpdated byVersion1_HorsesWed Apr 19 202371A_Horses_MiniTue May 23 202361GetGoodCookiesTue Mar 14 202331MiniMon Apr 10 20231A_List_SigTue Mar 21 20237TL Test Email 012Tue Mar 14 20231© Mirata Software LLC | 2023qa | 2.0.27 (9837) | 23-May-2023id(&quot;menu-&quot;)/div[@class=&quot;renderer-MuiPaper-root renderer-MuiMenu-paper renderer-MuiPopover-paper renderer-MuiPaper-elevation8 renderer-MuiPaper-rounded&quot;]/ul[@class=&quot;renderer-MuiList-root renderer-MuiMenu-list renderer-MuiList-padding&quot;]/li[@class=&quot;renderer-MuiButtonBase-root renderer-MuiListItem-root renderer-MuiMenuItem-root renderer-MuiMenuItem-gutters renderer-MuiListItem-gutters renderer-MuiListItem-button&quot;]FormTemplateNew FormBlankFrom ExistingType *​Name *DescriptionID *Workflow ID *CancelOKacme-id.form-type.terri-ype')]</value>
      <webElementGuid>e27627eb-b9a7-4f89-8ee3-b85b84f0d86d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
