<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_image-1</name>
   <tag></tag>
   <elementGuidId>c0133083-0808-41e8-b3e7-1dead4c8fa4d</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field-click-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='field-click-container']</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>16daabf6-3419-4828-ac83-cb72b5798c3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-click-container</value>
      <webElementGuid>3179cd9f-a649-4d3a-b20e-e29bc69ce7ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>f04e41d6-40b4-4e2a-a826-d522cee377d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>contenteditable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6f40b4ba-9119-4a83-b1b7-fc21cb437a1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>renderer-mirata-forms-249 react-resizable</value>
      <webElementGuid>76b54b24-44c6-41df-aa4a-d5ee3c16af6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>image-1</value>
      <webElementGuid>96c29f30-377b-499f-8885-15eed5732ff3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field-click-container&quot;)</value>
      <webElementGuid>9e7c8829-701c-4f8c-8daa-9d016395c78e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='field-click-container']</value>
      <webElementGuid>502711f6-efd5-47e3-8e62-f60af8ecc206</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='s4iTSE2UmAeoTAMAtfgtAx-presentation-dnd-wrapper-id']/div/div</value>
      <webElementGuid>7ede3569-9f3a-4150-a299-2cbc276b689f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Demo1'])[2]/following::div[3]</value>
      <webElementGuid>8330ec67-07ad-4c89-8b48-783de3199f72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Opens a URL'])[1]/following::div[14]</value>
      <webElementGuid>409ad171-8636-44be-934d-77794c4056e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show Hidden Fields'])[1]/preceding::div[24]</value>
      <webElementGuid>4312c629-462e-4bf3-802f-3afb7a3a0b2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/div/div/div/div/div/div/div/div/div</value>
      <webElementGuid>afce986f-de6e-4ff0-bf13-746ca282b4e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'field-click-container' and (text() = 'image-1' or . = 'image-1')]</value>
      <webElementGuid>2a8e1714-f0d9-4b98-914b-2822bbae3fb5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
