<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Decimal</name>
   <tag></tag>
   <elementGuidId>6bbb46af-408d-4167-bd8b-4c2e4f318536</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/amplify-authenticator/div[2]/div/div[4]/div/div/div/div[2]/div[2]/div/div[4]/div[2]/div</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>62a7745d-cafc-4bd6-a1de-63f1960b98da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-controls-section-control-label</value>
      <webElementGuid>e4c534bf-c92c-49bd-b242-356a3aa61201</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Decimal</value>
      <webElementGuid>b153b998-f76b-467a-b962-ff44be1b2944</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/amplify-authenticator[@class=&quot;hydrated&quot;]/div[@class=&quot;l-designer-wrapper&quot;]/div[@class=&quot;l-designer-grid&quot;]/div[@class=&quot;l-designer-panel-content left-dpc&quot;]/div[@class=&quot;c-panel-content&quot;]/div[1]/div[@class=&quot;control-selector-panel&quot;]/div[@class=&quot;control-selector-sections&quot;]/div[@class=&quot;a-controls-section&quot;]/div[@class=&quot;a-controls-section-body&quot;]/div[@class=&quot;a-controls-section-control&quot;]/div[@class=&quot;a-controls-section-control-text&quot;]/div[@class=&quot;a-controls-section-control-label&quot;]</value>
      <webElementGuid>724788b5-dc65-42f4-8087-c0187e76273f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/amplify-authenticator/div[2]/div/div[4]/div/div/div/div[2]/div[2]/div/div[4]/div[2]/div</value>
      <webElementGuid>b7f0a152-d361-4e5b-ae49-156cbded2495</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Whole number data input'])[1]/following::div[4]</value>
      <webElementGuid>0ea98432-4410-415a-8926-111d1ccb1c97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Number'])[1]/following::div[5]</value>
      <webElementGuid>bdaf5c1b-f91e-49bf-9f4b-7cb73e3d60c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Decimal data input'])[1]/preceding::div[1]</value>
      <webElementGuid>f550f485-a579-4b90-8899-3ecb7fd3397f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Checkbox'])[1]/preceding::div[3]</value>
      <webElementGuid>8d2f4a29-cc4f-405e-9321-40cf02f3a1b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Decimal']/parent::*</value>
      <webElementGuid>3786f36c-c04c-4b0c-8021-bc1f336c0a64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[4]/div[2]/div</value>
      <webElementGuid>36189a5e-ad9f-4f6a-889b-7ee3f23f4147</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Decimal' or . = 'Decimal')]</value>
      <webElementGuid>fc0e9792-d1ac-438f-839e-b96948bfb6ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
