<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Accept</name>
   <tag></tag>
   <elementGuidId>ca9a43f7-e169-41dd-8aa5-41d2dbabbe9e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.iubenda-cs-accept-btn.iubenda-cs-btn-primary.hover.focus</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='iubenda-cs-banner']/div/div/div/div[3]/div[2]/button[2]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ae280417-8ff6-4039-b772-b10022d03c38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iubenda-cs-accept-btn iubenda-cs-btn-primary hover focus</value>
      <webElementGuid>eb2ccef0-3014-409b-98c0-c81340be9535</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>82a29080-9bbd-4eb5-9e83-6fc41600f5ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b363a739-4346-4eb5-a760-66faf051910e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-pressed</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3c4a9c2e-c3b8-4719-b73f-f3a53b373510</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Accept</value>
      <webElementGuid>f9262b34-9ee6-42c4-a904-c1f374682bdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iubenda-cs-banner&quot;)/div[@class=&quot;iubenda-cs-container&quot;]/div[@class=&quot;iubenda-cs-content&quot;]/div[@class=&quot;iubenda-cs-rationale&quot;]/div[@class=&quot;iubenda-cs-opt-group&quot;]/div[@class=&quot;iubenda-cs-opt-group-consent&quot;]/button[@class=&quot;iubenda-cs-accept-btn iubenda-cs-btn-primary hover focus&quot;]</value>
      <webElementGuid>b1701baa-12a0-4a48-ae20-37e70bf566c0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='iubenda-cs-banner']/div/div/div/div[3]/div[2]/button[2]</value>
      <webElementGuid>c9772f45-8b99-4c90-b651-6c820b6561cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reject'])[1]/following::button[1]</value>
      <webElementGuid>c77d7c85-aae7-4df6-a02c-e6743a5f6ab7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Learn more and customize'])[1]/following::button[2]</value>
      <webElementGuid>c026d5e4-6175-4a04-95e1-beb2d127dbb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Accept']/parent::*</value>
      <webElementGuid>8e4eb287-e96b-49de-8fc8-06a89149bcae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button[2]</value>
      <webElementGuid>b2f3990b-aea3-42f3-8ed0-7964494b13a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Accept' or . = 'Accept')]</value>
      <webElementGuid>b9bc1ab4-affb-46c3-85c8-031de422f4d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
